export interface IProductParams {
    cate_id: number
    store_name: string
    store_info: string
    keyword: string
    unit_name: string
    bar_code: number
    image: string
    slider_image: string
    postage: number
    ot_price: number
    price: number
    sort: number
    stock: number
    sales: number
    ficti: number
    give_integral: number
    is_show: boolean
    cost: number
    is_hot: boolean
    is_benefit: boolean
    is_best: boolean
    is_new: boolean
    mer_use: boolean
    is_postage: boolean
    is_good: boolean
    spec_type: string
    items: string
    attrs: string
    coupon_ids: string
    label_id: string
    command_word: string
    recommend_image: string
    video_link: string
    temp_id: number
    activity: string
    description: string
}

export interface IProductQuery {
    page: number
    limit: number
    cate_id: number
    type: number
    store_name: string
    sales: string
}

export interface IProductData {
    id: number
    mer_id: number
    image: string
    recommend_image: string
    slider_image: string[]
    store_name: string
    store_info: string
    keyword: string
    bar_code: string
    cate_id: string
    price: string
    vip_price: string
    ot_price: string
    postage: string
    unit_name: string
    sort: number
    sales: number
    stock: string
    is_show: number
    is_hot: number
    is_benefit: number
    is_best: number
    is_new: number
    add_time: number
    is_postage: number
    is_del: number
    mer_use: number
    give_integral: string
    cost: string
    is_seckill: number
    is_bargain: number
    is_good: number
    is_sub: number
    is_vip: number
    ficti: number
    browse: number
    code_path: string
    soure_link: string
    video_link: string
    temp_id: number
    spec_type: number
    activity: string
    spu: string
    label_id: string
    command_word: string
    collect: number
    likes: number
    visitor: number
    cate_name: string
    stock_attr: boolean
}
